version: "3.3"

services:
  client:
    image: "heorh-denis/notes-client"
    restart: always
    build:
      context: ./
    ports:
      - "3000:3000"
    links:
      - server
  server:
    image: "heorh-denis/notes-server"
    restart: always
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_USER="${MONGO_USER}"
      - MONGO_PASSWORD="${MONGO_PASSWORD}"
